language: node_js
cache: npm
node_js:
- 8
sudo: false

# https://github.com/greenkeeperio/greenkeeper-lockfile#example-travis-ci-configurations
before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '8'
    before_install: true
    before_script: true
    after_script: true
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      email: sloria1@gmail.com
      api_key:
        secure: br200jQhQlEBnAGdjUdZ9QJr/jluG0W3HQj/nG0aTGoXdqW4u1BzrE4qPUDmrzWVtBDJhZMkHWboQEfoAr7HFNRQ1wXrgIt3AFNjkQsQyC5l1wNaqDlL3WbNhu4HD03yNwDhqA9+MGAiUG0zU6iOnN472YTuh4GN3kcDLKnBQq4tHC7fiDeSmFhM5dDqooBCR6qOczNoGNvxrly1PGV7T1vOnqKd2rmaD5Q6V508YLr+QcKtwZblrF3xWTBg0K18GN/B2RkIGP9xfj6CgDY/EnBF3xeFqwkUXJXnar+RFJP9z3MeDkgIfSawNFvD8axlyq7wXHkDaZEjVqghMi5FzkI2YCxDdMSG5Vqecev8LEEfaQ8kP9vBz/9oGXuDa1+qCySwMI2eoQcoJOn8zMp5953kI2EtaFMS1lqKn23vGjMLvS/6gYW8aCD2toOAoHy5P/gJqfd6cw8DR9ORDD/6QIfleSumkNU6CT9oNElsjQPAjg9zCheHqFFkcqPqe7sp9ig19Q39187V3gRopZMr2Da0XlN7tlm8UwKoOkuE6EFbGeMCyHB0/f/bF7dax80Rm+kbkqMYp0ONRiexHCKK2AGnU4MaT/mTm4h2MLWYcmH85ECuLRWmbDVtb07lPZd43KqCejjONUvPO1t2EMYc57EzRFFTwb+PRZvQcP6W4bY=
      on:
        tags: true
        repo: sloria/jrnl-parse
env:
  global:
    secure: W1ZLFlIvLbbxP2QV+qZBLT/lX6o5M/x1vl5Z+Aa0/NGxrwhQ7qfDBDwmttmve9aDBtvPRxPFBcNtTKmLlLWM+bbl2ssGbAPR6Y5StzguxClZGgM+4ygJPfjskT6wMx9sAt0CSSldvXsUEfs74icoEuW+eDgxAQfuVudMKkOpQgynDUVlOSdEgbMVjmxRsAIBFrsWgRnAWHEVrSGXBBG02WhlRdjUvLw+Jhr8CsVQawuswGVI8HX8MBY8vZX54pypXDAenkGqrTw3XG3VliK2Luj4sRDQqnYxbWEAq1m2sp31KQgegZpH9jg2vBJAtcOXgp/LKS5/tpHcpPdaHMVta0V7p9PRrVoSPMV5NUb3ytM1os8qhCMH2/uT3RtevBMuNHYKJymTVBdJefOinY2xqRM2eZAfLJtPVEAxN21EAzeyIViK3UUNvsxs/kKcT6MvwzocqUr9aoZzbAY8lDdo72Im4jh4pBgPBP7jugXcbmoBcVU09G+ux0SziWqYzgcWbQ3Nbq3sISizxTN8odNAg+7xuMttAy4HmisOOOdV9Sv3ZTtOxQqZ3NhT8tUkc0Az1Gov37JKD+JxaAjar2T41r+e0Eyb/UvwUgVUy1PjR1I5/g8tt5peqQcTRDR7wphGYstnpbzqvlmQBHmF+YvMyffxpkWr38OawL6TwqH7+5c=
